In [44]:
import pandas as pd
import os
import ast
import re
import warnings
warnings.filterwarnings('ignore')

In [45]:
list_name = os.listdir('./')

In [71]:
def process_string_to_dict(string):
    string = string.split('; Count')[0]
    # Substituir os `;` por vírgulas e remover espaços extras
    formatted_string = re.sub(r";", ",", string)
    formatted_string = re.sub(r"=", ":", formatted_string)
    # Adicionar chaves externas para transformá-la em um dicionário
    formatted_string = "{" + formatted_string + "}"
    # Substituir chaves como "Code.or.Value" por "Code" e "Value.Description" por "Description"
    formatted_string = re.sub(r"Code\.or\.Value", '"Code"', formatted_string)
    formatted_string = re.sub(r"Value\.Description", '"Description"', formatted_string)

    return eval(formatted_string)



list_name_types = ['demo', 'diet', 'exam', 'lab', 'q']
list_names_file = ['DEMO_tabelas_lab_completas_resultados.csv', 'DIET_tabelas_lab_completas_resultados.csv', 'EXAM_tabelas_lab_completas_resultados.csv',
                   'LAB_tabelas_lab_completas_resultados.csv', 'Q_tabelas_lab_completas_resultados.csv']

for idx, type in enumerate(list_name_types):
    file = list_names_file[idx]
    tab_main = pd.read_csv(f'./{file}')
    
    dict_list = tab_main.apply(lambda row: {'name': row['Data.File.Name'], 'begin': str(row['Begin.Year']), 'end': str(row['EndYear'])}, axis=1).tolist()
    
    table_names = tab_main['Data.File.Name'].tolist()
    
    
    for current_name in table_names:
        print(f"***************************{current_name}************************")
        try:
        
            df_now = pd.read_csv(f'./{type}/{type.upper()}-{current_name.upper()}.csv')
            resultado = [d for d in dict_list if d['name'] == current_name]
            
            df_sem_duplicatas = df_now.drop_duplicates()
            codebook_select_col = df_sem_duplicatas[['Tabela','Variable_Name', 'SAS_Label', 'Tabela_Valores','English_Text', 'Target', 'English_Instructions']]
            list_Variable_Name = codebook_select_col['Variable_Name'].unique()
            
            df_codebook_final = pd.DataFrame()
            for variable in list_Variable_Name:
                df_now = codebook_select_col[codebook_select_col['Variable_Name']==variable]
                list_english = list(df_now['English_Text'].unique())
                list_Target = list(df_now['Target'].unique())
                list_English_Instructions = list(df_now['English_Instructions'].unique())
                df_now['English_Text'] = str(list_english[0])
                df_now['Target'] = str(list_Target[0])
                df_now['English_Instructions'] = str(list_English_Instructions[0])

                df_codebook_final = pd.concat([df_codebook_final, df_now])
                
            rows = []
            for _, row in df_codebook_final.iterrows():
                # Ignorar linhas onde Tabela_Valores é NaN
                if pd.isna(row['Tabela_Valores']):
                    rows.append({
                                "Column": row["Variable_Name"],
                                "Code": None,
                                "Label": None,
                                "English_Text": row["English_Text"],
                                "Target": row["Target"],
                                "English_Instructions": row["English_Instructions"]
                            })
                    continue
                
                # Extrair os dados de Code e Value.Description
                valores = row['Tabela_Valores']
                valores = re.sub(r'\s+', ' ', valores)
                valores = re.sub(r':\s+\[', ': [', valores)
                
                try:
                    # Usando ast.literal_eval para transformar a string em dicionário
                    parsed_values = process_string_to_dict(valores)
                    codes = parsed_values["Code"]
                    codes = [str(item).title() for item in codes]
                    descriptions = parsed_values["Description"]
                    descriptions = [str(item).title() for item in descriptions]
                    
                    # Criar uma nova linha para cada combinação de Code e Description
                    for code, description in zip(codes, descriptions):
                        rows.append({
                            "Column": row["Variable_Name"],
                            "Code": code,
                            "Label": description,
                            "English_Text": row["English_Text"],
                            "Target": row["Target"],
                            "English_Instructions": row["English_Instructions"]
                        })
                        
                except Exception as e:
                    print(f"Erro ao processar a linha: {row['Tabela_Valores']}")
                    print(e)

            # Criar um novo DataFrame com os dados processados
            df_expanded = pd.DataFrame(rows)
            df_expanded['Class'] = None
            df_expanded['Other For'] = None
                
            df_expanded.drop_duplicates(inplace=True)

            caminho = f"{type}/SDDs"

            # Verifica se a pasta existe, se não, cria
            if not os.path.exists(caminho):
                os.makedirs(caminho)
                print(f"Pasta criada: {caminho}")
            else:
                print(f"A pasta já existe: {caminho}")


            print(resultado[0]['begin'])
            begin = resultado[0]['begin']
            end = resultado[0]['end']
            df_expanded.to_csv(f'./{type}/SDDs/CODEBOOK-NHANES-{begin}-{end}-{current_name}.csv', sep=',', encoding='utf-8')
            
            
            
            dictionary_mapping = codebook_select_col[['Variable_Name']]
            dictionary_mapping = dictionary_mapping.drop_duplicates(subset='Variable_Name', keep='first')

            dictionary_mapping['Attribute'] = None
            dictionary_mapping['attributeOf'] = None
            dictionary_mapping['Unit'] = None
            dictionary_mapping['Time'] = None
            dictionary_mapping['Entity'] = None
            dictionary_mapping['Role'] = None
            dictionary_mapping['Relation'] = None
            dictionary_mapping['inRelationTo'] = None
            dictionary_mapping['wasDerivedFrom'] = None
            dictionary_mapping['Maturity'] = None
            dictionary_mapping['Template'] = None
            dictionary_mapping['wasGeneratedBy'] = None
            dictionary_mapping.reset_index(inplace=True, drop=True)
            dictionary_mapping.rename(columns={"Variable_Name": "Column"}, inplace=True)
            
            dictionary_mapping.to_csv(f'./{type}/SDDs/dictionary_mapping-NHANES-{begin}-{end}-{current_name}.csv', sep=',', encoding='utf-8')
            
            
            with pd.ExcelWriter(f'./{type}/SDDs/SDD-NHANES-{begin}-{end}-{current_name}.xlsx', engine='xlsxwriter') as writer:
                df_expanded.to_excel(writer, sheet_name='codebook', index=False)
                dictionary_mapping.to_excel(writer, sheet_name='dictionary_mapping', index=False)
                
        except Exception as e:
            print(f"Erro ao processar a tabela {current_name}")

***************************DEMO************************
A pasta já existe: demo/SDDs
1999
***************************DEMO_B************************
A pasta já existe: demo/SDDs
2001
***************************DEMO_C************************
A pasta já existe: demo/SDDs
2003
***************************DEMO_D************************
A pasta já existe: demo/SDDs
2005
***************************DEMO_E************************
A pasta já existe: demo/SDDs
2007
***************************DEMO_F************************
A pasta já existe: demo/SDDs
2009
***************************DEMO_G************************
A pasta já existe: demo/SDDs
2011
***************************DEMO_H************************
A pasta já existe: demo/SDDs
2013
***************************DEMO_I************************
A pasta já existe: demo/SDDs
2015
***************************DEMO_J************************
A pasta já existe: demo/SDDs
2017
***************************P_DEMO************************
A pasta já existe: demo/SDDs
2017
***************************DEMO_L************************
A pasta já existe: demo/SDDs
2021
***************************DRXFMT************************
A pasta já existe: diet/SDDs
1999
***************************DRXIFF************************
A pasta já existe: diet/SDDs
1999
***************************DRXTOT************************
A pasta já existe: diet/SDDs
1999
***************************DSBI************************
A pasta já existe: diet/SDDs
1999
***************************DSII************************
Erro ao processar a tabela DSII
***************************DSPI************************
Erro ao processar a tabela DSPI
***************************DSQFILE1************************
A pasta já existe: diet/SDDs
1999
***************************DSQFILE2************************
A pasta já existe: diet/SDDs
1999
***************************DRXFMT_B************************
A pasta já existe: diet/SDDs
2001
***************************DRXIFF_B************************
A pasta já existe: diet/SDDs
2001
***************************DRXTOT_B************************
A pasta já existe: diet/SDDs
2001
***************************DSQ1_B************************
A pasta já existe: diet/SDDs
2001
***************************DSQ2_B************************
A pasta já existe: diet/SDDs
2001
***************************DR1IFF_C************************
A pasta já existe: diet/SDDs
2003
***************************DR1TOT_C************************
A pasta já existe: diet/SDDs
2003
***************************DR2IFF_C************************
A pasta já existe: diet/SDDs
2003
***************************DR2TOT_C************************
A pasta já existe: diet/SDDs
2003
***************************DRXFCD_C************************
A pasta já existe: diet/SDDs
2003
***************************DRXMCD_C************************
A pasta já existe: diet/SDDs
2003
***************************DSQ1_C************************
A pasta já existe: diet/SDDs
2003
***************************DSQ2_C************************
A pasta já existe: diet/SDDs
2003
***************************FFQDC_C************************
A pasta já existe: diet/SDDs
2003
***************************FFQRAW_C************************
A pasta já existe: diet/SDDs
2003
***************************FOODLK_C************************
A pasta já existe: diet/SDDs
2003
***************************VARLK_C************************
A pasta já existe: diet/SDDs
2003
***************************DR1IFF_D************************
A pasta já existe: diet/SDDs
2005
***************************DR1TOT_D************************
A pasta já existe: diet/SDDs
2005
***************************DR2IFF_D************************
A pasta já existe: diet/SDDs
2005
***************************DR2TOT_D************************
A pasta já existe: diet/SDDs
2005
***************************DRXFCD_D************************
A pasta já existe: diet/SDDs
2005
***************************DRXMCD_D************************
A pasta já existe: diet/SDDs
2005
***************************DSQ1_D************************
A pasta já existe: diet/SDDs
2005
***************************DSQ2_D************************
A pasta já existe: diet/SDDs
2005
***************************FFQDC_D************************
A pasta já existe: diet/SDDs
2005
***************************FFQRAW_D************************
A pasta já existe: diet/SDDs
2005
***************************FOODLK_D************************
A pasta já existe: diet/SDDs
2005
***************************VARLK_D************************
A pasta já existe: diet/SDDs
2005
***************************DR1IFF_E************************
A pasta já existe: diet/SDDs
2007
***************************DR1TOT_E************************
A pasta já existe: diet/SDDs
2007
***************************DR2IFF_E************************
A pasta já existe: diet/SDDs
2007
***************************DR2TOT_E************************
A pasta já existe: diet/SDDs
2007
***************************DRXFCD_E************************
A pasta já existe: diet/SDDs
2007
***************************DRXMCD_E************************
A pasta já existe: diet/SDDs
2007
***************************DS1IDS_E************************
A pasta já existe: diet/SDDs
2007
***************************DS1TOT_E************************
A pasta já existe: diet/SDDs
2007
***************************DS2IDS_E************************
A pasta já existe: diet/SDDs
2007
***************************DS2TOT_E************************
A pasta já existe: diet/SDDs
2007
***************************DSQIDS_E************************
A pasta já existe: diet/SDDs
2007
***************************DSQTOT_E************************
A pasta já existe: diet/SDDs
2007
***************************DR1IFF_F************************
A pasta já existe: diet/SDDs
2009
***************************DR1TOT_F************************
A pasta já existe: diet/SDDs
2009
***************************DR2IFF_F************************
A pasta já existe: diet/SDDs
2009
***************************DR2TOT_F************************
A pasta já existe: diet/SDDs
2009
***************************DRXFCD_F************************
A pasta já existe: diet/SDDs
2009
***************************DRXMCD_F************************
A pasta já existe: diet/SDDs
2009
***************************DS1IDS_F************************
A pasta já existe: diet/SDDs
2009
***************************DS1TOT_F************************
A pasta já existe: diet/SDDs
2009
***************************DS2IDS_F************************
A pasta já existe: diet/SDDs
2009
***************************DS2TOT_F************************
A pasta já existe: diet/SDDs
2009
***************************DSQIDS_F************************
A pasta já existe: diet/SDDs
2009
***************************DSQTOT_F************************
A pasta já existe: diet/SDDs
2009
***************************DTQ_F************************
A pasta já existe: diet/SDDs
2009
***************************DR1IFF_G************************
A pasta já existe: diet/SDDs
2011
***************************DR1TOT_G************************
A pasta já existe: diet/SDDs
2011
***************************DR2IFF_G************************
A pasta já existe: diet/SDDs
2011
***************************DR2TOT_G************************
A pasta já existe: diet/SDDs
2011
***************************DRXFCD_G************************
A pasta já existe: diet/SDDs
2011
***************************DRXMCD_G************************
A pasta já existe: diet/SDDs
2011
***************************DS1IDS_G************************
A pasta já existe: diet/SDDs
2011
***************************DS1TOT_G************************
A pasta já existe: diet/SDDs
2011
***************************DS2IDS_G************************
A pasta já existe: diet/SDDs
2011
***************************DS2TOT_G************************
A pasta já existe: diet/SDDs
2011
***************************DSQIDS_G************************
A pasta já existe: diet/SDDs
2011
***************************DSQTOT_G************************
A pasta já existe: diet/SDDs
2011
***************************DR1IFF_H************************
A pasta já existe: diet/SDDs
2013
***************************DR1TOT_H************************
A pasta já existe: diet/SDDs
2013
***************************DR2IFF_H************************
A pasta já existe: diet/SDDs
2013
***************************DR2TOT_H************************
A pasta já existe: diet/SDDs
2013
***************************DRXFCD_H************************
Erro ao processar a tabela DRXFCD_H
***************************DS1IDS_H************************
A pasta já existe: diet/SDDs
2013
***************************DS1TOT_H************************
A pasta já existe: diet/SDDs
2013
***************************DS2IDS_H************************
A pasta já existe: diet/SDDs
2013
***************************DS2TOT_H************************
A pasta já existe: diet/SDDs
2013
***************************DSQIDS_H************************
A pasta já existe: diet/SDDs
2013
***************************DSQTOT_H************************
A pasta já existe: diet/SDDs
2013
***************************DR1IFF_I************************
A pasta já existe: diet/SDDs
2015
***************************DR1TOT_I************************
A pasta já existe: diet/SDDs
2015
***************************DR2IFF_I************************
A pasta já existe: diet/SDDs
2015
***************************DR2TOT_I************************
A pasta já existe: diet/SDDs
2015
***************************DRXFCD_I************************
A pasta já existe: diet/SDDs
2015
***************************DS1IDS_I************************
A pasta já existe: diet/SDDs
2015
***************************DS1TOT_I************************
A pasta já existe: diet/SDDs
2015
***************************DS2IDS_I************************
A pasta já existe: diet/SDDs
2015
***************************DS2TOT_I************************
A pasta já existe: diet/SDDs
2015
***************************DSQIDS_I************************
A pasta já existe: diet/SDDs
2015
***************************DSQTOT_I************************
A pasta já existe: diet/SDDs
2015
***************************DR1IFF_J************************
A pasta já existe: diet/SDDs
2017
***************************DR1TOT_J************************
A pasta já existe: diet/SDDs
2017
***************************DR2IFF_J************************
A pasta já existe: diet/SDDs
2017
***************************DR2TOT_J************************
A pasta já existe: diet/SDDs
2017
***************************DRXFCD_J************************
A pasta já existe: diet/SDDs
2017
***************************DS1IDS_J************************
A pasta já existe: diet/SDDs
2017
***************************DS1TOT_J************************
A pasta já existe: diet/SDDs
2017
***************************DS2IDS_J************************
A pasta já existe: diet/SDDs
2017
***************************DS2TOT_J************************
A pasta já existe: diet/SDDs
2017
***************************DSQIDS_J************************
A pasta já existe: diet/SDDs
2017
***************************DSQTOT_J************************
A pasta já existe: diet/SDDs
2017
***************************P_DR1IFF************************
A pasta já existe: diet/SDDs
2017
***************************P_DR1TOT************************
A pasta já existe: diet/SDDs
2017
***************************P_DR2IFF************************
A pasta já existe: diet/SDDs
2017
***************************P_DR2TOT************************
A pasta já existe: diet/SDDs
2017
***************************P_DRXFCD************************
A pasta já existe: diet/SDDs
2017
***************************P_DS1IDS************************
A pasta já existe: diet/SDDs
2017
***************************P_DS1TOT************************
A pasta já existe: diet/SDDs
2017
***************************P_DS2IDS************************
A pasta já existe: diet/SDDs
2017
***************************P_DS2TOT************************
A pasta já existe: diet/SDDs
2017
***************************P_DSQIDS************************
A pasta já existe: diet/SDDs
2017
***************************P_DSQTOT************************
A pasta já existe: diet/SDDs
2017
***************************DR1IFF_L************************
A pasta já existe: diet/SDDs
2021
***************************DR1TOT_L************************
A pasta já existe: diet/SDDs
2021
***************************DR2IFF_L************************
A pasta já existe: diet/SDDs
2021
***************************DR2TOT_L************************
A pasta já existe: diet/SDDs
2021
***************************DRXFCD_L************************
A pasta já existe: diet/SDDs
2021
***************************AUX1************************
A pasta já existe: exam/SDDs
1999
***************************AUXAR************************
A pasta já existe: exam/SDDs
1999
***************************AUXTYM************************
A pasta já existe: exam/SDDs
1999
***************************BAX************************
A pasta já existe: exam/SDDs
1999
***************************BIX************************
A pasta já existe: exam/SDDs
1999
***************************BMX************************
A pasta já existe: exam/SDDs
1999
***************************BPX************************
A pasta já existe: exam/SDDs
1999
***************************CVX************************
A pasta já existe: exam/SDDs
1999
***************************LEXABPI************************
A pasta já existe: exam/SDDs
1999
***************************LEXPN************************
A pasta já existe: exam/SDDs
1999
***************************MSX************************
Erro ao processar a linha: Code.or.Value=["1", "2", "3", "4", "5", "6", "."]; Value.Description=["Chest/abdomen surgery past three weeks", "Myocardial infarction (or"heart attack") in the past six weeks", "Told by dr had aneurysm in the brain or had a stroke", "Have severe neck or back pain today", "Difficult in bending or straightening right knee", "Had right knee or right hip replacement", "Missing"]; Count=["10", "3", "99", "88", "25", "32", "1899"]; Cumulative=["10", "13", "112", "200", "225", "257", "2156"]; Skip.to.Item=["NA", "NA", "NA", "NA", "NA", "NA", "NA"]
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
A pasta já existe: exam/SDDs
1999
***************************OHXDENT************************
A pasta já existe: exam/SDDs
1999
***************************OHXPERIO************************
A pasta já existe: exam/SDDs
1999
***************************OHXREF************************
A pasta já existe: exam/SDDs
1999
***************************SEQ************************
A pasta já existe: exam/SDDs
1999
***************************TB************************
A pasta já existe: exam/SDDs
1999
***************************VIX************************
A pasta já existe: exam/SDDs
1999
***************************AUX_B************************
A pasta já existe: exam/SDDs
2001
***************************AUXAR_B************************
A pasta já existe: exam/SDDs
2001
***************************AUXTYM_B************************
A pasta já existe: exam/SDDs
2001
***************************BAX_B************************
A pasta já existe: exam/SDDs
2001
***************************BIX_B************************
A pasta já existe: exam/SDDs
2001
***************************BMX_B************************
A pasta já existe: exam/SDDs
2001
***************************BPX_B************************
A pasta já existe: exam/SDDs
2001
***************************CVX_B************************
A pasta já existe: exam/SDDs
2001
***************************DXX_2_B************************
A pasta já existe: exam/SDDs
2001
***************************LEXAB_B************************
A pasta já existe: exam/SDDs
2001
***************************LEXPN_B************************
A pasta já existe: exam/SDDs
2001
***************************MSX_B************************
Erro ao processar a linha: Code.or.Value=["1", "2", "3", "4", "5", "6", "."]; Value.Description=["Chest/abdomen surgery past three weeks", "Myocardial infarction (or"heart attack") in the past six weeks", "Told by dr had aneurysm in the brain or had a stroke", "Have severe neck or back pain today", "Difficult in bending or straightening right knee", "Had right knee or right hip replacement", "Missing"]; Count=["12", "8", "102", "38", "69", "64", "2000"]; Cumulative=["12", "20", "122", "160", "229", "293", "2293"]; Skip.to.Item=["NA", "NA", "NA", "NA", "NA", "NA", "NA"]
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
A pasta já existe: exam/SDDs
2001
***************************OHXDEN_B************************
A pasta já existe: exam/SDDs
2001
***************************OHXPRL_B************************
A pasta já existe: exam/SDDs
2001
***************************OHXPRU_B************************
A pasta já existe: exam/SDDs
2001
***************************OHXREF_B************************
A pasta já existe: exam/SDDs
2001
***************************VIX_B************************
A pasta já existe: exam/SDDs
2001
***************************AUX_C************************
A pasta já existe: exam/SDDs
2003
***************************AUXAR_C************************
A pasta já existe: exam/SDDs
2003
***************************AUXTYM_C************************
A pasta já existe: exam/SDDs
2003
***************************BAX_C************************
A pasta já existe: exam/SDDs
2003
***************************BIX_C************************
A pasta já existe: exam/SDDs
2003
***************************BMX_C************************
A pasta já existe: exam/SDDs
2003
***************************BPX_C************************
A pasta já existe: exam/SDDs
2003
***************************CVX_C************************
A pasta já existe: exam/SDDs
2003
***************************DEX_C************************
A pasta já existe: exam/SDDs
2003
***************************DXXAG_C************************
A pasta já existe: exam/SDDs
2003
***************************LEXAB_C************************
A pasta já existe: exam/SDDs
2003
***************************LEXPN_C************************
A pasta já existe: exam/SDDs
2003
***************************OHXADD_C************************
A pasta já existe: exam/SDDs
2003
***************************OHXDEN_C************************
A pasta já existe: exam/SDDs
2003
***************************OHXPRL_C************************
A pasta já existe: exam/SDDs
2003
***************************OHXPRU_C************************
A pasta já existe: exam/SDDs
2003
***************************OHXREF_C************************
A pasta já existe: exam/SDDs
2003
***************************VIX_C************************
A pasta já existe: exam/SDDs
2003
***************************AUX_D************************
A pasta já existe: exam/SDDs
2005
***************************AUXAR_D************************
A pasta já existe: exam/SDDs
2005
***************************AUXTYM_D************************
A pasta já existe: exam/SDDs
2005
***************************BMX_D************************
A pasta já existe: exam/SDDs
2005
***************************BPX_D************************
A pasta já existe: exam/SDDs
2005
***************************DXXAG_D************************
A pasta já existe: exam/SDDs
2005
***************************DXXFEM_D************************
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "3", "4", "5", "6", "."]; Value.Description=["Valid data", "Jewelry or other objects not removed", "Non-removable objects (includes prostheses, implants)", "Excessive x-ray "noise" due to obesity", "Body parts out of scan region", "Positioning problem", "Other (includes panniculus, participant motion, unknown artifacts)", "Missing"]; Count=["6076", "0", "3", "3", "28", "3", "325", "1282"]; Cumulative=["6076", "6076", "6079", "6082", "6110", "6113", "6438", "7720"]; Skip.to.Item=["NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA"]
invalid syntax. Perhaps you forgot a comma? (<string>, line 1)
A pasta já existe: exam/SDDs
2005

In [39]:
resultado[0]['begin']

'2021'

In [51]:
tab_main_MSX = pd.read_csv('./exam/MSX.csv')

FileNotFoundError: [Errno 2] No such file or directory: './exam/MSX.csv'

In [ ]:
df_now = pd.read_csv(f'./{type}/{type.upper()}-{current_name.upper()}.csv')

In [72]:
tab_demo = pd.read_csv('./q/Q-P_DBQ.csv')
tab_demo

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,English_Instructions,Tabela_Valores
0,P_DBQ,CBQ596,CBQ596,Heard of My Plate,Next Im going to ask a few questions about the...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
1,P_DBQ,CBQ606,CBQ606,Looked up My Plate on internet,{Have you/Has SP} looked up the My Plate plan ...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
2,P_DBQ,CBQ611,CBQ611,Tried My Plate plan,{Have you/Has SP} tried to follow the recommen...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
3,P_DBQ,DBD030,DBD030,Age stopped breastfeeding(days),How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
4,P_DBQ,DBD041,DBD041,Age first fed formula(days),How old was {SP} when {he/she} was first fed f...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 365"", ""0"", ""666666"", ""777..."
5,P_DBQ,DBD050,DBD050,Age stopped receiving formula(days),How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
6,P_DBQ,DBD055,DBD055,Age started other food/beverage,This next question is about the first thing th...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 730"", ""0"", ""666666"", ""777..."
7,P_DBQ,DBD061,DBD061,Age first fed milk(days),How old was {SP} when {he/she} was first fed m...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
8,P_DBQ,DBD381,DBD381,# of times/week get school lunch,During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ..."
9,P_DBQ,DBD411,DBD411,# of times/week get school breakfast,During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ..."
10,P_DBQ,DBD895,DBD895,# of meals not home prepared,Next Im going to ask you about meals. By meal ...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""7777"", ""9999"", ""."", ""1 to 21"",..."
11,P_DBQ,DBD900,DBD900,# of meals from fast food or pizza place,How many of those meals {did you/did SP} get f...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 21"", ""0"", ""5555"", ""7777"",..."
12,P_DBQ,DBD905,DBD905,# of ready-to-eat foods in past 30 days,Some grocery stores sell ready to eat foods su...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",..."
13,P_DBQ,DBD910,DBD910,# of frozen meals/pizza in past 30 days,During the past 30 days how often did you {SP}...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",..."
14,P_DBQ,DBQ010,DBQ010,Ever breastfed or fed breastmilk,Now Im going to ask you some general questions...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
15,P_DBQ,DBQ073A,DBQ073A,Type of milk first fed - whole milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D..."
16,P_DBQ,DBQ073B,DBQ073B,Type of milk first fed - 2% milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""11"", "".""]; Value.Description=[..."
17,P_DBQ,DBQ073C,DBQ073C,Type of milk first fed - 1% milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""12"", "".""]; Value.Description=[..."
18,P_DBQ,DBQ073D,DBQ073D,Type of milk first fed - fat free milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""13"", "".""]; Value.Description=[..."
19,P_DBQ,DBQ073E,DBQ073E,Type of milk first fed - soy milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""14"", "".""]; Value.Description=[..."
20,P_DBQ,DBQ073U,DBQ073U,Type of milk first fed - other,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""30"", "".""]; Value.Description=[..."
21,P_DBQ,DBQ197,DBQ197,Past 30 day milk product consumption,Now Im going to ask a few questions about milk...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
22,P_DBQ,DBQ223A,DBQ223A,You drink whole or regular milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D..."
23,P_DBQ,DBQ223B,DBQ223B,You drink 2% fat milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""11"", "".""]; Value.Description=[..."
24,P_DBQ,DBQ223C,DBQ223C,You drink 1% fat milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""12"", "".""]; Value.Description=[..."
25,P_DBQ,DBQ223D,DBQ223D,You drink fat free/skim milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""13"", "".""]; Value.Description=[..."
26,P_DBQ,DBQ223E,DBQ223E,You drink soy milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""14"", "".""]; Value.Description=[..."
27,P_DBQ,DBQ223U,DBQ223U,You drink another type of milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""30"", "".""]; Value.Description=[..."
28,P_DBQ,DBQ229,DBQ229,Regular milk use 5 times per week,The next question is about regular milk use. A...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
29,P_DBQ,DBQ235A,DBQ235A,How often drank milk age 5-12,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
30,P_DBQ,DBQ235B,DBQ235B,How often drank milk age 13-17,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
31,P_DBQ,DBQ235C,DBQ235C,How often drank milk age 18-35,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
32,P_DBQ,DBQ301,DBQ301,Community/Government meals delivered,The next questions are about meals provided by...,Both males and females 60 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
33,P_DBQ,DBQ330,DBQ330,Eat meals at Community/Senior center,In the past 12 months did {you/SP} go to a com...,Both males and females 60 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
34,P_DBQ,DBQ360,DBQ360,Attend kindergarten thru high school,During the school year {do you/does SP} attend...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
35,P_DBQ,DBQ370,DBQ370,School serves school lunches,Does {your/SPs} school serve school lunches? T...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
36,P_DBQ,DBQ390,DBQ390,School lunch free reduced or full price,{Do you/Does SP} get these lunches free at a r...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
37,P_DBQ,DBQ400,DBQ400,School serve complete breakfast each day,Does {your/SPs} school serve a complete breakf...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
38,P_DBQ,DBQ421,DBQ421,School breakfast free/reduced/full price,{Do you/Does SP} get these breakfasts free at ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
39,P_DBQ,DBQ424,DBQ424,Summer program meal free/reduced price,(Do you/Does SP) get a free or reduced price m...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
40,P_DBQ,DBQ700,DBQ700,How healthy is the diet,Next I have some questions about {your/SP?s} e...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""5"", ""7"", ""..."
41,P_DBQ,DBQ930,DBQ930,Main meal planner/preparer,{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
42,P_DBQ,DBQ935,DBQ935,Shared meal planning/preparing duty,{Do you/Does SP} share in the planning or prep...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
43,P_DBQ,DBQ940,DBQ940,Main food shopper,{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
44,P_DBQ,DBQ945,DBQ945,Shared food shopping duty,{Do you/Does SP} share in the shopping for foo...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
45,P_DBQ,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS,NaN,NaN

In [12]:
tab_demo = pd.read_csv('./demo/DEMO-DEMO.csv')
tab_demo

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,English_Instructions,Tabela_Valores
0,DEMO,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS,NaN,NaN
1,DEMO,SDDSRVYR,SDDSRVYR,Data Release Number,Data Release Number.,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", "".""]; Value.Description=[""..."
2,DEMO,RIDSTATR,RIDSTATR,Interview/Examination Status,Interview and Examination Status of the Sample...,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
3,DEMO,RIDEXMON,RIDEXMON,Six month time period,Six month time period when the examination was...,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
4,DEMO,RIAGENDR,RIAGENDR,Gender,Gender of the sample person,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
...,...,...,...,...,...,...,...,...
139,DEMO,WTIREP48,WTIREP48,Interview Weight Jack Knife Replicate 48,Interview Weight Jack Knife Replicate 48,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0 to 237147.54679"", "".""]; Valu..."
140,DEMO,WTIREP49,WTIREP49,Interview Weight Jack Knife Replicate 49,Interview Weight Jack Knife Replicate 49,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0 to 237076.10369"", "".""]; Valu..."
141,DEMO,WTIREP50,WTIREP50,Interview Weight Jack Knife Replicate 50,Interview Weight Jack Knife Replicate 50,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0 to 238360.24085"", "".""]; Valu..."
142,DEMO,WTIREP51,WTIREP51,Interview Weight Jack Knife Replicate 51,Interview Weight Jack Knife Replicate 51,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0 to 236648.97986"", "".""]; Valu..."
143,DEMO,WTIREP52,WTIREP52,Interview Weight Jack Knife Replicate 52,Interview Weight Jack Knife Replicate 52,Both males and females 0 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0 to 236964.16066"", "".""]; Valu..."

In [73]:
df_sem_duplicatas = tab_demo.drop_duplicates()
df_sem_duplicatas

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,English_Instructions,Tabela_Valores
0,P_DBQ,CBQ596,CBQ596,Heard of My Plate,Next Im going to ask a few questions about the...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
1,P_DBQ,CBQ606,CBQ606,Looked up My Plate on internet,{Have you/Has SP} looked up the My Plate plan ...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
2,P_DBQ,CBQ611,CBQ611,Tried My Plate plan,{Have you/Has SP} tried to follow the recommen...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
3,P_DBQ,DBD030,DBD030,Age stopped breastfeeding(days),How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
4,P_DBQ,DBD041,DBD041,Age first fed formula(days),How old was {SP} when {he/she} was first fed f...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 365"", ""0"", ""666666"", ""777..."
5,P_DBQ,DBD050,DBD050,Age stopped receiving formula(days),How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
6,P_DBQ,DBD055,DBD055,Age started other food/beverage,This next question is about the first thing th...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 730"", ""0"", ""666666"", ""777..."
7,P_DBQ,DBD061,DBD061,Age first fed milk(days),How old was {SP} when {he/she} was first fed m...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77..."
8,P_DBQ,DBD381,DBD381,# of times/week get school lunch,During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ..."
9,P_DBQ,DBD411,DBD411,# of times/week get school breakfast,During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ..."
10,P_DBQ,DBD895,DBD895,# of meals not home prepared,Next Im going to ask you about meals. By meal ...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""7777"", ""9999"", ""."", ""1 to 21"",..."
11,P_DBQ,DBD900,DBD900,# of meals from fast food or pizza place,How many of those meals {did you/did SP} get f...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 21"", ""0"", ""5555"", ""7777"",..."
12,P_DBQ,DBD905,DBD905,# of ready-to-eat foods in past 30 days,Some grocery stores sell ready to eat foods su...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",..."
13,P_DBQ,DBD910,DBD910,# of frozen meals/pizza in past 30 days,During the past 30 days how often did you {SP}...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",..."
14,P_DBQ,DBQ010,DBQ010,Ever breastfed or fed breastmilk,Now Im going to ask you some general questions...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
15,P_DBQ,DBQ073A,DBQ073A,Type of milk first fed - whole milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D..."
16,P_DBQ,DBQ073B,DBQ073B,Type of milk first fed - 2% milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""11"", "".""]; Value.Description=[..."
17,P_DBQ,DBQ073C,DBQ073C,Type of milk first fed - 1% milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""12"", "".""]; Value.Description=[..."
18,P_DBQ,DBQ073D,DBQ073D,Type of milk first fed - fat free milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""13"", "".""]; Value.Description=[..."
19,P_DBQ,DBQ073E,DBQ073E,Type of milk first fed - soy milk,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""14"", "".""]; Value.Description=[..."
20,P_DBQ,DBQ073U,DBQ073U,Type of milk first fed - other,What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN,"Code.or.Value=[""30"", "".""]; Value.Description=[..."
21,P_DBQ,DBQ197,DBQ197,Past 30 day milk product consumption,Now Im going to ask a few questions about milk...,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
22,P_DBQ,DBQ223A,DBQ223A,You drink whole or regular milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D..."
23,P_DBQ,DBQ223B,DBQ223B,You drink 2% fat milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""11"", "".""]; Value.Description=[..."
24,P_DBQ,DBQ223C,DBQ223C,You drink 1% fat milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""12"", "".""]; Value.Description=[..."
25,P_DBQ,DBQ223D,DBQ223D,You drink fat free/skim milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""13"", "".""]; Value.Description=[..."
26,P_DBQ,DBQ223E,DBQ223E,You drink soy milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""14"", "".""]; Value.Description=[..."
27,P_DBQ,DBQ223U,DBQ223U,You drink another type of milk,What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""30"", "".""]; Value.Description=[..."
28,P_DBQ,DBQ229,DBQ229,Regular milk use 5 times per week,The next question is about regular milk use. A...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
29,P_DBQ,DBQ235A,DBQ235A,How often drank milk age 5-12,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
30,P_DBQ,DBQ235B,DBQ235B,How often drank milk age 13-17,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
31,P_DBQ,DBQ235C,DBQ235C,How often drank milk age 18-35,Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""..."
32,P_DBQ,DBQ301,DBQ301,Community/Government meals delivered,The next questions are about meals provided by...,Both males and females 60 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
33,P_DBQ,DBQ330,DBQ330,Eat meals at Community/Senior center,In the past 12 months did {you/SP} go to a com...,Both males and females 60 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
34,P_DBQ,DBQ360,DBQ360,Attend kindergarten thru high school,During the school year {do you/does SP} attend...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
35,P_DBQ,DBQ370,DBQ370,School serves school lunches,Does {your/SPs} school serve school lunches? T...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
36,P_DBQ,DBQ390,DBQ390,School lunch free reduced or full price,{Do you/Does SP} get these lunches free at a r...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
37,P_DBQ,DBQ400,DBQ400,School serve complete breakfast each day,Does {your/SPs} school serve a complete breakf...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
38,P_DBQ,DBQ421,DBQ421,School breakfast free/reduced/full price,{Do you/Does SP} get these breakfasts free at ...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
39,P_DBQ,DBQ424,DBQ424,Summer program meal free/reduced price,(Do you/Does SP) get a free or reduced price m...,Both males and females 4 YEARS - 19 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ..."
40,P_DBQ,DBQ700,DBQ700,How healthy is the diet,Next I have some questions about {your/SP?s} e...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""5"", ""7"", ""..."
41,P_DBQ,DBQ930,DBQ930,Main meal planner/preparer,{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
42,P_DBQ,DBQ935,DBQ935,Shared meal planning/preparing duty,{Do you/Does SP} share in the planning or prep...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
43,P_DBQ,DBQ940,DBQ940,Main food shopper,{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
44,P_DBQ,DBQ945,DBQ945,Shared food shopping duty,{Do you/Does SP} share in the shopping for foo...,Both males and females 16 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value..."
45,P_DBQ,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS,NaN,NaN

In [74]:
codebook_select_col = df_sem_duplicatas[['Tabela','Variable_Name', 'SAS_Label', 'Tabela_Valores','English_Text', 'Target', 'English_Instructions']]

In [75]:
codebook_select_col

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target,English_Instructions
0,P_DBQ,CBQ596,Heard of My Plate,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",Next Im going to ask a few questions about the...,Both males and females 16 YEARS - 150 YEARS,NaN
1,P_DBQ,CBQ606,Looked up My Plate on internet,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Have you/Has SP} looked up the My Plate plan ...,Both males and females 16 YEARS - 150 YEARS,NaN
2,P_DBQ,CBQ611,Tried My Plate plan,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Have you/Has SP} tried to follow the recommen...,Both males and females 16 YEARS - 150 YEARS,NaN
3,P_DBQ,DBD030,Age stopped breastfeeding(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN
4,P_DBQ,DBD041,Age first fed formula(days),"Code.or.Value=[""1 to 365"", ""0"", ""666666"", ""777...",How old was {SP} when {he/she} was first fed f...,Both males and females 0 YEARS - 6 YEARS,NaN
5,P_DBQ,DBD050,Age stopped receiving formula(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",How old was {SP} when {he/she} completely stop...,Both males and females 0 YEARS - 6 YEARS,NaN
6,P_DBQ,DBD055,Age started other food/beverage,"Code.or.Value=[""1 to 730"", ""0"", ""666666"", ""777...",This next question is about the first thing th...,Both males and females 0 YEARS - 6 YEARS,NaN
7,P_DBQ,DBD061,Age first fed milk(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",How old was {SP} when {he/she} was first fed m...,Both males and females 0 YEARS - 6 YEARS,NaN
8,P_DBQ,DBD381,# of times/week get school lunch,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ...",During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN
9,P_DBQ,DBD411,# of times/week get school breakfast,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ...",During the school year about how many times a ...,Both males and females 4 YEARS - 19 YEARS,NaN
10,P_DBQ,DBD895,# of meals not home prepared,"Code.or.Value=[""7777"", ""9999"", ""."", ""1 to 21"",...",Next Im going to ask you about meals. By meal ...,Both males and females 1 YEARS - 150 YEARS,NaN
11,P_DBQ,DBD900,# of meals from fast food or pizza place,"Code.or.Value=[""1 to 21"", ""0"", ""5555"", ""7777"",...",How many of those meals {did you/did SP} get f...,Both males and females 1 YEARS - 150 YEARS,NaN
12,P_DBQ,DBD905,# of ready-to-eat foods in past 30 days,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",...",Some grocery stores sell ready to eat foods su...,Both males and females 1 YEARS - 150 YEARS,NaN
13,P_DBQ,DBD910,# of frozen meals/pizza in past 30 days,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",...",During the past 30 days how often did you {SP}...,Both males and females 1 YEARS - 150 YEARS,NaN
14,P_DBQ,DBQ010,Ever breastfed or fed breastmilk,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",Now Im going to ask you some general questions...,Both males and females 0 YEARS - 6 YEARS,NaN
15,P_DBQ,DBQ073A,Type of milk first fed - whole milk,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
16,P_DBQ,DBQ073B,Type of milk first fed - 2% milk,"Code.or.Value=[""11"", "".""]; Value.Description=[...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
17,P_DBQ,DBQ073C,Type of milk first fed - 1% milk,"Code.or.Value=[""12"", "".""]; Value.Description=[...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
18,P_DBQ,DBQ073D,Type of milk first fed - fat free milk,"Code.or.Value=[""13"", "".""]; Value.Description=[...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
19,P_DBQ,DBQ073E,Type of milk first fed - soy milk,"Code.or.Value=[""14"", "".""]; Value.Description=[...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
20,P_DBQ,DBQ073U,Type of milk first fed - other,"Code.or.Value=[""30"", "".""]; Value.Description=[...",What type of milk was {SP} first fed on a dail...,Both males and females 0 YEARS - 6 YEARS,NaN
21,P_DBQ,DBQ197,Past 30 day milk product consumption,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",Now Im going to ask a few questions about milk...,Both males and females 1 YEARS - 150 YEARS,NaN
22,P_DBQ,DBQ223A,You drink whole or regular milk,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
23,P_DBQ,DBQ223B,You drink 2% fat milk,"Code.or.Value=[""11"", "".""]; Value.Description=[...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
24,P_DBQ,DBQ223C,You drink 1% fat milk,"Code.or.Value=[""12"", "".""]; Value.Description=[...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
25,P_DBQ,DBQ223D,You drink fat free/skim milk,"Code.or.Value=[""13"", "".""]; Value.Description=[...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
26,P_DBQ,DBQ223E,You drink soy milk,"Code.or.Value=[""14"", "".""]; Value.Description=[...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
27,P_DBQ,DBQ223U,You drink another type of milk,"Code.or.Value=[""30"", "".""]; Value.Description=[...",What type of milk was it? Was it usually . . .,Both males and females 1 YEARS - 150 YEARS,NaN
28,P_DBQ,DBQ229,Regular milk use 5 times per week,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",The next question is about regular milk use. A...,Both males and females 20 YEARS - 150 YEARS,NaN
29,P_DBQ,DBQ235A,How often drank milk age 5-12,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN
30,P_DBQ,DBQ235B,How often drank milk age 13-17,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN
31,P_DBQ,DBQ235C,How often drank milk age 18-35,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",Now Im going to ask you how often {you/SP} dra...,Both males and females 20 YEARS - 150 YEARS,NaN
32,P_DBQ,DBQ301,Community/Government meals delivered,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",The next questions are about meals provided by...,Both males and females 60 YEARS - 150 YEARS,NaN
33,P_DBQ,DBQ330,Eat meals at Community/Senior center,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",In the past 12 months did {you/SP} go to a com...,Both males and females 60 YEARS - 150 YEARS,NaN
34,P_DBQ,DBQ360,Attend kindergarten thru high school,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",During the school year {do you/does SP} attend...,Both males and females 4 YEARS - 19 YEARS,NaN
35,P_DBQ,DBQ370,School serves school lunches,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",Does {your/SPs} school serve school lunches? T...,Both males and females 4 YEARS - 19 YEARS,NaN
36,P_DBQ,DBQ390,School lunch free reduced or full price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",{Do you/Does SP} get these lunches free at a r...,Both males and females 4 YEARS - 19 YEARS,NaN
37,P_DBQ,DBQ400,School serve complete breakfast each day,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",Does {your/SPs} school serve a complete breakf...,Both males and females 4 YEARS - 19 YEARS,NaN
38,P_DBQ,DBQ421,School breakfast free/reduced/full price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",{Do you/Does SP} get these breakfasts free at ...,Both males and females 4 YEARS - 19 YEARS,NaN
39,P_DBQ,DBQ424,Summer program meal free/reduced price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",(Do you/Does SP) get a free or reduced price m...,Both males and females 4 YEARS - 19 YEARS,NaN
40,P_DBQ,DBQ700,How healthy is the diet,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""5"", ""7"", ""...",Next I have some questions about {your/SP?s} e...,Both males and females 16 YEARS - 150 YEARS,NaN
41,P_DBQ,DBQ930,Main meal planner/preparer,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN
42,P_DBQ,DBQ935,Shared meal planning/preparing duty,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Do you/Does SP} share in the planning or prep...,Both males and females 16 YEARS - 150 YEARS,NaN
43,P_DBQ,DBQ940,Main food shopper,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Are you/Is SP} the person who does most of th...,Both males and females 16 YEARS - 150 YEARS,NaN
44,P_DBQ,DBQ945,Shared food shopping duty,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",{Do you/Does SP} share in the shopping for foo...,Both males and females 16 YEARS - 150 YEARS,NaN
45,P_DBQ,SEQN,Respondent sequence number,NaN,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS,NaN

In [76]:
list_Variable_Name = codebook_select_col['Variable_Name'].unique()
df_codebook_final = pd.DataFrame()

for variable in list_Variable_Name:
    df_now = codebook_select_col[codebook_select_col['Variable_Name']==variable]
    list_english = list(df_now['English_Text'].unique())
    list_Target = list(df_now['Target'].unique())
    list_English_Instructions = list(df_now['English_Instructions'].unique())
    df_now['English_Text'] = str(list_english)
    df_now['Target'] = str(list_Target)
    df_now['English_Instructions'] = str(list_English_Instructions)

    df_codebook_final = pd.concat([df_codebook_final, df_now])

In [77]:
df_codebook_final

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target,English_Instructions
0,P_DBQ,CBQ596,Heard of My Plate,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['Next Im going to ask a few questions about t...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
1,P_DBQ,CBQ606,Looked up My Plate on internet,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Have you/Has SP} looked up the My Plate pla...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
2,P_DBQ,CBQ611,Tried My Plate plan,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Have you/Has SP} tried to follow the recomm...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
3,P_DBQ,DBD030,Age stopped breastfeeding(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",['How old was {SP} when {he/she} completely st...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
4,P_DBQ,DBD041,Age first fed formula(days),"Code.or.Value=[""1 to 365"", ""0"", ""666666"", ""777...",['How old was {SP} when {he/she} was first fed...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
5,P_DBQ,DBD050,Age stopped receiving formula(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",['How old was {SP} when {he/she} completely st...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
6,P_DBQ,DBD055,Age started other food/beverage,"Code.or.Value=[""1 to 730"", ""0"", ""666666"", ""777...",['This next question is about the first thing ...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
7,P_DBQ,DBD061,Age first fed milk(days),"Code.or.Value=[""1 to 1095"", ""0"", ""666666"", ""77...",['How old was {SP} when {he/she} was first fed...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
8,P_DBQ,DBD381,# of times/week get school lunch,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ...",['During the school year about how many times ...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
9,P_DBQ,DBD411,# of times/week get school breakfast,"Code.or.Value=[""1 to 5"", ""0"", ""7777"", ""9999"", ...",['During the school year about how many times ...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
10,P_DBQ,DBD895,# of meals not home prepared,"Code.or.Value=[""7777"", ""9999"", ""."", ""1 to 21"",...",['Next Im going to ask you about meals. By mea...,['Both males and females 1 YEARS - 150 YEARS'],[nan]
11,P_DBQ,DBD900,# of meals from fast food or pizza place,"Code.or.Value=[""1 to 21"", ""0"", ""5555"", ""7777"",...",['How many of those meals {did you/did SP} get...,['Both males and females 1 YEARS - 150 YEARS'],[nan]
12,P_DBQ,DBD905,# of ready-to-eat foods in past 30 days,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",...",['Some grocery stores sell ready to eat foods ...,['Both males and females 1 YEARS - 150 YEARS'],[nan]
13,P_DBQ,DBD910,# of frozen meals/pizza in past 30 days,"Code.or.Value=[""1 to 90"", ""0"", ""6666"", ""7777"",...",['During the past 30 days how often did you {S...,['Both males and females 1 YEARS - 150 YEARS'],[nan]
14,P_DBQ,DBQ010,Ever breastfed or fed breastmilk,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['Now Im going to ask you some general questio...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
15,P_DBQ,DBQ073A,Type of milk first fed - whole milk,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
16,P_DBQ,DBQ073B,Type of milk first fed - 2% milk,"Code.or.Value=[""11"", "".""]; Value.Description=[...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
17,P_DBQ,DBQ073C,Type of milk first fed - 1% milk,"Code.or.Value=[""12"", "".""]; Value.Description=[...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
18,P_DBQ,DBQ073D,Type of milk first fed - fat free milk,"Code.or.Value=[""13"", "".""]; Value.Description=[...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
19,P_DBQ,DBQ073E,Type of milk first fed - soy milk,"Code.or.Value=[""14"", "".""]; Value.Description=[...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
20,P_DBQ,DBQ073U,Type of milk first fed - other,"Code.or.Value=[""30"", "".""]; Value.Description=[...",['What type of milk was {SP} first fed on a da...,['Both males and females 0 YEARS - 6 YEARS'],[nan]
21,P_DBQ,DBQ197,Past 30 day milk product consumption,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",['Now Im going to ask a few questions about mi...,['Both males and females 1 YEARS - 150 YEARS'],[nan]
22,P_DBQ,DBQ223A,You drink whole or regular milk,"Code.or.Value=[""10"", ""77"", ""99"", "".""]; Value.D...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
23,P_DBQ,DBQ223B,You drink 2% fat milk,"Code.or.Value=[""11"", "".""]; Value.Description=[...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
24,P_DBQ,DBQ223C,You drink 1% fat milk,"Code.or.Value=[""12"", "".""]; Value.Description=[...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
25,P_DBQ,DBQ223D,You drink fat free/skim milk,"Code.or.Value=[""13"", "".""]; Value.Description=[...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
26,P_DBQ,DBQ223E,You drink soy milk,"Code.or.Value=[""14"", "".""]; Value.Description=[...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
27,P_DBQ,DBQ223U,You drink another type of milk,"Code.or.Value=[""30"", "".""]; Value.Description=[...",['What type of milk was it? Was it usually . ....,['Both males and females 1 YEARS - 150 YEARS'],[nan]
28,P_DBQ,DBQ229,Regular milk use 5 times per week,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",['The next question is about regular milk use....,['Both males and females 20 YEARS - 150 YEARS'],[nan]
29,P_DBQ,DBQ235A,How often drank milk age 5-12,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",['Now Im going to ask you how often {you/SP} d...,['Both males and females 20 YEARS - 150 YEARS'],[nan]
30,P_DBQ,DBQ235B,How often drank milk age 13-17,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",['Now Im going to ask you how often {you/SP} d...,['Both males and females 20 YEARS - 150 YEARS'],[nan]
31,P_DBQ,DBQ235C,How often drank milk age 18-35,"Code.or.Value=[""0"", ""1"", ""2"", ""3"", ""4"", ""7"", ""...",['Now Im going to ask you how often {you/SP} d...,['Both males and females 20 YEARS - 150 YEARS'],[nan]
32,P_DBQ,DBQ301,Community/Government meals delivered,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['The next questions are about meals provided ...,['Both males and females 60 YEARS - 150 YEARS'],[nan]
33,P_DBQ,DBQ330,Eat meals at Community/Senior center,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['In the past 12 months did {you/SP} go to a c...,['Both males and females 60 YEARS - 150 YEARS'],[nan]
34,P_DBQ,DBQ360,Attend kindergarten thru high school,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['During the school year {do you/does SP} atte...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
35,P_DBQ,DBQ370,School serves school lunches,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['Does {your/SPs} school serve school lunches?...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
36,P_DBQ,DBQ390,School lunch free reduced or full price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",['{Do you/Does SP} get these lunches free at a...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
37,P_DBQ,DBQ400,School serve complete breakfast each day,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['Does {your/SPs} school serve a complete brea...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
38,P_DBQ,DBQ421,School breakfast free/reduced/full price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",['{Do you/Does SP} get these breakfasts free a...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
39,P_DBQ,DBQ424,Summer program meal free/reduced price,"Code.or.Value=[""1"", ""2"", ""3"", ""7"", ""9"", "".""]; ...",['(Do you/Does SP) get a free or reduced price...,['Both males and females 4 YEARS - 19 YEARS'],[nan]
40,P_DBQ,DBQ700,How healthy is the diet,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""5"", ""7"", ""...",['Next I have some questions about {your/SP?s}...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
41,P_DBQ,DBQ930,Main meal planner/preparer,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Are you/Is SP} the person who does most of ...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
42,P_DBQ,DBQ935,Shared meal planning/preparing duty,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Do you/Does SP} share in the planning or pr...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
43,P_DBQ,DBQ940,Main food shopper,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Are you/Is SP} the person who does most of ...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
44,P_DBQ,DBQ945,Shared food shopping duty,"Code.or.Value=[""1"", ""2"", ""7"", ""9"", "".""]; Value...",['{Do you/Does SP} share in the shopping for f...,['Both males and females 16 YEARS - 150 YEARS'],[nan]
45,P_DBQ,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan]

In [78]:
def process_string_to_dict(string):
    string = string.split('; Count')[0]
    # Substituir os `;` por vírgulas e remover espaços extras
    formatted_string = re.sub(r";", ",", string)
    formatted_string = re.sub(r"=", ":", formatted_string)
    # Adicionar chaves externas para transformá-la em um dicionário
    formatted_string = "{" + formatted_string + "}"
    # Substituir chaves como "Code.or.Value" por "Code" e "Value.Description" por "Description"
    formatted_string = re.sub(r"Code\.or\.Value", '"Code"', formatted_string)
    formatted_string = re.sub(r"Value\.Description", '"Description"', formatted_string)

    return eval(formatted_string)

In [82]:
rows = []
for _, row in df_codebook_final.iterrows():
    # Ignorar linhas onde Tabela_Valores é NaN
    if pd.isna(row['Tabela_Valores']):
        rows.append({
                    "Column": row["Variable_Name"],
                    "Code": None,
                    "Label": None,
                    "English_Text": row["English_Text"],
                    "Target": row["Target"],
                    "English_Instructions": row["English_Instructions"]
                })
        continue
    
    # Extrair os dados de Code e Value.Description
    valores = row['Tabela_Valores']
    
    print()
    print(valores)
    #print(valores.replace("\n", ""))
    valores = re.sub(r'\s+', ' ', valores)
    valores = re.sub(r':\s+\[', ': [', valores)
    valores = valores.replace('"', "'")
    
    print(valores)
    
    # Usando ast.literal_eval para transformar a string em dicionário
    parsed_values = process_string_to_dict(valores)
    codes = parsed_values["Code"]
    codes = [str(item).title() for item in codes]
    descriptions = parsed_values["Description"]
    descriptions = [str(item).title() for item in descriptions]
    # Criar uma nova linha para cada combinação de Code e Description
    print()
    print("********************************")
    print(codes)
    print(descriptions)
    print("********************************")
    print(row)
    
    for code, description in zip(codes, descriptions):
        rows.append({
            "Column": row["Variable_Name"],
            "Code": code,
            "Label": description,
            "English_Text": row["English_Text"],
            "Target": row["Target"],
            "English_Instructions": row["English_Instructions"]
        })


# Criar um novo DataFrame com os dados processados
df_expanded = pd.DataFrame(rows)
df_expanded['Class'] = None
df_expanded['Other For'] = None

Code.or.Value=["1", "2", "7", "9", "."]; Value.Description=["Yes", "No", "Refused", "Don't know", "Missing"]; Count=["2361", "7811", "0", "23", "5365"]; Cumulative=["2361", "10172", "10172", "10195", "15560"]; Skip.to.Item=["", "DBQ930", "DBQ930", "DBQ930", ""]
Code.or.Value=['1', '2', '7', '9', '.']; Value.Description=['Yes', 'No', 'Refused', 'Don't know', 'Missing']; Count=['2361', '7811', '0', '23', '5365']; Cumulative=['2361', '10172', '10172', '10195', '15560']; Skip.to.Item=['', 'DBQ930', 'DBQ930', 'DBQ930', '']

SyntaxError: unterminated string literal (detected at line 1) (<string>, line 1)

In [21]:
df_expanded

,Column,Code,Label,English_Text,Target,English_Instructions,Class,Other For
0,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
1,SDDSRVYR,1,Nhanes 1999-2000 Public Release,['Data Release Number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
2,SDDSRVYR,.,Missing,['Data Release Number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
3,RIDSTATR,1,Interviewed Only,['Interview and Examination Status of the Samp...,['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
4,RIDSTATR,2,Both Interviewed And Mec Examined,['Interview and Examination Status of the Samp...,['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
...,...,...,...,...,...,...,...,...
414,WTIREP50,.,Missing,['Interview Weight Jack Knife Replicate 50'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
415,WTIREP51,0 To 236648.97986,Range Of Values,['Interview Weight Jack Knife Replicate 51'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
416,WTIREP51,.,Missing,['Interview Weight Jack Knife Replicate 51'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
417,WTIREP52,0 To 236964.16066,Range Of Values,['Interview Weight Jack Knife Replicate 52'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
418,WTIREP52,.,Missing,['Interview Weight Jack Knife Replicate 52'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None

In [22]:
df_expanded.drop_duplicates(inplace=True)

In [23]:
df_expanded

,Column,Code,Label,English_Text,Target,English_Instructions,Class,Other For
0,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
1,SDDSRVYR,1,Nhanes 1999-2000 Public Release,['Data Release Number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
2,SDDSRVYR,.,Missing,['Data Release Number.'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
3,RIDSTATR,1,Interviewed Only,['Interview and Examination Status of the Samp...,['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
4,RIDSTATR,2,Both Interviewed And Mec Examined,['Interview and Examination Status of the Samp...,['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
...,...,...,...,...,...,...,...,...
414,WTIREP50,.,Missing,['Interview Weight Jack Knife Replicate 50'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
415,WTIREP51,0 To 236648.97986,Range Of Values,['Interview Weight Jack Knife Replicate 51'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
416,WTIREP51,.,Missing,['Interview Weight Jack Knife Replicate 51'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
417,WTIREP52,0 To 236964.16066,Range Of Values,['Interview Weight Jack Knife Replicate 52'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None
418,WTIREP52,.,Missing,['Interview Weight Jack Knife Replicate 52'],['Both males and females 0 YEARS - 150 YEARS'],[nan],None,None

In [18]:
df_expanded.to_csv('DEMO_codebook.csv', sep=',', encoding='utf-8')

In [23]:
dictionary_mapping

,Variable_Name,Attribute,attributeOf,Unit,Time,Entity,Role,Relation,inRelationTo,wasDerivedFrom,wasGeneratedBy
0,SEQN,None,None,None,None,None,None,None,None,None,None
1,SDDSRVYR,None,None,None,None,None,None,None,None,None,None
2,RIDSTATR,None,None,None,None,None,None,None,None,None,None
3,RIDEXMON,None,None,None,None,None,None,None,None,None,None
4,RIAGENDR,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
174,DMDMARTZ,None,None,None,None,None,None,None,None,None,None
175,DMDYRUSZ,None,None,None,None,None,None,None,None,None,None
176,WTINTPRP,None,None,None,None,None,None,None,None,None,None
177,WTMECPRP,None,None,None,None,None,None,None,None,None,None
178,DMDYRUSR,None,None,None,None,None,None,None,None,None,None