In [1]:
import pandas as pd
import os
import ast
import re

In [2]:
list_name = os.listdir('./')

In [3]:
list_name

['DEMO_codebook.csv',
 'DEMO_dictionary_mapping.csv',
 'demo_script.ipynb',
 'nhanes_codebook_resultados_com_tabelas.csv',
 'P_DEMO_DEMO.csv',
 'tabelas_completas.csv']

In [4]:
nhanes_codebook = pd.read_csv('nhanes_codebook_resultados_com_tabelas.csv')

In [5]:
df_sem_duplicatas = nhanes_codebook.drop_duplicates()
df_sem_duplicatas

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,Tabela_Valores
0,DEMO,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS,NaN
1,DEMO,SDDSRVYR,SDDSRVYR,Data Release Number,Data Release Number.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""1"", "".""]; Value.Description=[""..."
2,DEMO,RIDSTATR,RIDSTATR,Interview/Examination Status,Interview and Examination Status of the Sample...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
3,DEMO,RIDEXMON,RIDEXMON,Six month time period,Six month time period when the examination was...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
4,DEMO,RIAGENDR,RIAGENDR,Gender,Gender of the sample person,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
...,...,...,...,...,...,...,...
593,DEMO_L,WTINT2YR,WTINT2YR,Full sample 2-year interview weight,Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""4584.463196 to 170968.343177"",..."
594,DEMO_L,WTMEC2YR,WTMEC2YR,Full sample 2-year MEC exam weight,Full sample 2 year MEC exam weight.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""4581.595095 to 227108.296958"",..."
595,DEMO_L,SDMVSTRA,SDMVSTRA,Masked variance pseudo-stratum,Masked variance unit pseudo-stratum variable f...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""173 to 187"", "".""]; Value.Descr..."
596,DEMO_L,SDMVPSU,SDMVPSU,Masked variance pseudo-PSU,Masked variance unit pseudo-PSU variable for v...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""1 to 2"", "".""]; Value.Descripti..."
597,DEMO_L,INDFMPIR,INDFMPIR,Ratio of family income to poverty,Ratio of family income to poverty,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."

In [6]:
df_sem_duplicatas[df_sem_duplicatas['Variavel']=='INDFMPIR']

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,Tabela_Valores
22,DEMO,INDFMPIR,INDFMPIR,Family PIR,Poverty income ratio (PIR) - a ratio of family...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
166,DEMO_B,INDFMPIR,INDFMPIR,Family PIR,Poverty income ratio (PIR) - a ratio of family...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
203,DEMO_C,INDFMPIR,INDFMPIR,Family PIR,Poverty income ratio (PIR) - a ratio of family...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
246,DEMO_D,INDFMPIR,INDFMPIR,Family PIR,Poverty income ratio (PIR) - a ratio of family...,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
289,DEMO_E,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty threshold,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
332,DEMO_F,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty threshold,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
390,DEMO_G,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty guidelines.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
448,DEMO_H,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty guidelines.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
495,DEMO_I,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty guidelines.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."
541,DEMO_J,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty guidelines.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.98"", ""5"", "".""]; Value.D..."
550,P_DEMO,INDFMPIR,INDFMPIR,Ratio of family income to poverty,A ratio of family income to poverty guidelines.,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.98"", ""5"", "".""]; Value.D..."
597,DEMO_L,INDFMPIR,INDFMPIR,Ratio of family income to poverty,Ratio of family income to poverty,Both males and females 0 YEARS - 150 YEARS,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D..."

In [7]:
codebook_select_col = df_sem_duplicatas[['Tabela','Variable_Name', 'SAS_Label', 'Tabela_Valores','English_Text', 'Target']]

In [8]:
codebook_select_col

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
0,DEMO,SEQN,Respondent sequence number,NaN,Respondent sequence number.,Both males and females 0 YEARS - 150 YEARS
1,DEMO,SDDSRVYR,Data Release Number,"Code.or.Value=[""1"", "".""]; Value.Description=[""...",Data Release Number.,Both males and females 0 YEARS - 150 YEARS
2,DEMO,RIDSTATR,Interview/Examination Status,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti...",Interview and Examination Status of the Sample...,Both males and females 0 YEARS - 150 YEARS
3,DEMO,RIDEXMON,Six month time period,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti...",Six month time period when the examination was...,Both males and females 0 YEARS - 150 YEARS
4,DEMO,RIAGENDR,Gender,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti...",Gender of the sample person,Both males and females 0 YEARS - 150 YEARS
...,...,...,...,...,...,...
593,DEMO_L,WTINT2YR,Full sample 2-year interview weight,"Code.or.Value=[""4584.463196 to 170968.343177"",...",Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS
594,DEMO_L,WTMEC2YR,Full sample 2-year MEC exam weight,"Code.or.Value=[""4581.595095 to 227108.296958"",...",Full sample 2 year MEC exam weight.,Both males and females 0 YEARS - 150 YEARS
595,DEMO_L,SDMVSTRA,Masked variance pseudo-stratum,"Code.or.Value=[""173 to 187"", "".""]; Value.Descr...",Masked variance unit pseudo-stratum variable f...,Both males and females 0 YEARS - 150 YEARS
596,DEMO_L,SDMVPSU,Masked variance pseudo-PSU,"Code.or.Value=[""1 to 2"", "".""]; Value.Descripti...",Masked variance unit pseudo-PSU variable for v...,Both males and females 0 YEARS - 150 YEARS
597,DEMO_L,INDFMPIR,Ratio of family income to poverty,"Code.or.Value=[""0 to 4.99"", ""5"", "".""]; Value.D...",Ratio of family income to poverty,Both males and females 0 YEARS - 150 YEARS

In [9]:
codebook_select_col[codebook_select_col['Variable_Name']=='WTINT2YR']

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
31,DEMO,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""974.66525161 to 236864.13597"",...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
175,DEMO_B,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""1492.093618 to 201188.12151"", ...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
221,DEMO_C,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""1498.994197 to 156319.65778"", ...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
264,DEMO_D,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""1224.968032 to 152162.42158"", ...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
307,DEMO_E,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""2359.373828 to 186295.50665"", ...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
350,DEMO_F,WTINT2YR,Full Sample 2 Year Interview Weight,"Code.or.Value=[""3279.931789 to 153810.25883"", ...",Interviewed Sample Persons.,Both males and females 0 YEARS - 150 YEARS
384,DEMO_G,WTINT2YR,Full sample 2 year interview weight,"Code.or.Value=[""3320.8855 to 220233.3152"", "".""...",Interviewed participants.,Both males and females 0 YEARS - 150 YEARS
442,DEMO_H,WTINT2YR,Full sample 2 year interview weight,"Code.or.Value=[""3697.772098 to 167884.54371"", ...",Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS
489,DEMO_I,WTINT2YR,Full sample 2 year interview weight,"Code.or.Value=[""3293.928267 to 233755.84185"", ...",Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS
535,DEMO_J,WTINT2YR,Full sample 2 year interview weight,"Code.or.Value=[""2571.0687123 to 433085.00526"",...",Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS
593,DEMO_L,WTINT2YR,Full sample 2-year interview weight,"Code.or.Value=[""4584.463196 to 170968.343177"",...",Full sample 2 year interview weight.,Both males and females 0 YEARS - 150 YEARS

In [10]:
list_Variable_Name = codebook_select_col['Variable_Name'].unique()
df_codebook_final = pd.DataFrame()

for variable in list_Variable_Name:
    df_now = codebook_select_col[codebook_select_col['Variable_Name']==variable]
    list_english = list(df_now['English_Text'].unique())
    list_Target = list(df_now['Target'].unique())
    df_now['English_Text'] = str(list_english)
    df_now['Target'] = str(list_Target)

    df_codebook_final = pd.concat([df_codebook_final, df_now])

C:\Users\l-oen\AppData\Local\Temp\ipykernel_21732\571734007.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_now['English_Text'] = str(list_english)
C:\Users\l-oen\AppData\Local\Temp\ipykernel_21732\571734007.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_now['Target'] = str(list_Target)

In [11]:
df_codebook_final

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
0,DEMO,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS']
144,DEMO_B,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS']
181,DEMO_C,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS']
225,DEMO_D,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS']
268,DEMO_E,SEQN,Respondent sequence number,NaN,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS']
...,...,...,...,...,...,...
585,DEMO_L,DMDMARTZ,Marital status,"Code.or.Value=[""1"", ""2"", ""3"", ""77"", ""99"", "".""]...",['Marital status'],['Both males and females 20 YEARS - 150 YEARS']
546,P_DEMO,DMDYRUSZ,Length of time in US,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""77"", ""99"",...",['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS']
569,P_DEMO,WTINTPRP,Full sample interview weight,"Code.or.Value=[""1017.784203 to 338363.60019"", ...",['Full sample interview weight'],['Both males and females 0 YEARS - 150 YEARS']
570,P_DEMO,WTMECPRP,Full sample MEC exam weight,"Code.or.Value=[""0 to 367555.74298"", "".""]; Valu...",['Full sample MEC exam weight'],['Both males and females 0 YEARS - 150 YEARS']
583,DEMO_L,DMDYRUSR,Length of time in US,"Code.or.Value=[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""...",['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS']

In [12]:
def process_string_to_dict(string):
    string = string.split('; Count')[0]
    # Substituir os `;` por vírgulas e remover espaços extras
    formatted_string = re.sub(r";", ",", string)
    formatted_string = re.sub(r"=", ":", formatted_string)
    # Adicionar chaves externas para transformá-la em um dicionário
    formatted_string = "{" + formatted_string + "}"
    # Substituir chaves como "Code.or.Value" por "Code" e "Value.Description" por "Description"
    formatted_string = re.sub(r"Code\.or\.Value", '"Code"', formatted_string)
    formatted_string = re.sub(r"Value\.Description", '"Description"', formatted_string)

    return eval(formatted_string)

In [14]:
rows = []
for _, row in df_codebook_final.iterrows():
    # Ignorar linhas onde Tabela_Valores é NaN
    if pd.isna(row['Tabela_Valores']):
        rows.append({
                    "Column": row["Variable_Name"],
                    "Code": None,
                    "Label": None,
                    "English_Text": row["English_Text"],
                    "Target": row["Target"]
                })
        continue
    
    # Extrair os dados de Code e Value.Description
    valores = row['Tabela_Valores']
    
    try:
        # Usando ast.literal_eval para transformar a string em dicionário
        parsed_values = process_string_to_dict(valores)
        codes = parsed_values["Code"]
        codes = [str(item).title() for item in codes]
        descriptions = parsed_values["Description"]
        descriptions = [str(item).title() for item in descriptions]
        # Criar uma nova linha para cada combinação de Code e Description
        for code, description in zip(codes, descriptions):
            rows.append({
                "Column": row["Variable_Name"],
                "Code": code,
                "Label": description,
                "English_Text": row["English_Text"],
                "Target": row["Target"]
            })
    except Exception as e:
        print(f"Erro ao processar a linha: {row['Tabela_Valores']}")
        print(e)

# Criar um novo DataFrame com os dados processados
df_expanded = pd.DataFrame(rows)
df_expanded['Class'] = None
df_expanded['Other For'] = None

In [15]:
df_expanded

,Column,Code,Label,English_Text,Target,Class,Other For
0,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
1,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
2,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
3,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
4,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
...,...,...,...,...,...,...,...
2687,DMDYRUSR,5,15 To 19 Years,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2688,DMDYRUSR,6,20 Years Or More,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2689,DMDYRUSR,77,Refused,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2690,DMDYRUSR,99,Don'T Know,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2691,DMDYRUSR,.,Missing,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None

In [16]:
df_expanded.drop_duplicates(inplace=True)

In [17]:
df_expanded

,Column,Code,Label,English_Text,Target,Class,Other For
0,SEQN,None,None,['Respondent sequence number.'],['Both males and females 0 YEARS - 150 YEARS'],None,None
12,SDDSRVYR,1,Nhanes 1999-2000 Public Release,"['Data Release Number.', 'Data release cycle']",['Both males and females 0 YEARS - 150 YEARS'],None,None
13,SDDSRVYR,.,Missing,"['Data Release Number.', 'Data release cycle']",['Both males and females 0 YEARS - 150 YEARS'],None,None
14,SDDSRVYR,2,Nhanes 2001-2002 Public Release,"['Data Release Number.', 'Data release cycle']",['Both males and females 0 YEARS - 150 YEARS'],None,None
16,SDDSRVYR,3,Nhanes 2003-2004 Public Release,"['Data Release Number.', 'Data release cycle']",['Both males and females 0 YEARS - 150 YEARS'],None,None
...,...,...,...,...,...,...,...
2687,DMDYRUSR,5,15 To 19 Years,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2688,DMDYRUSR,6,20 Years Or More,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2689,DMDYRUSR,77,Refused,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2690,DMDYRUSR,99,Don'T Know,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None
2691,DMDYRUSR,.,Missing,['Length of time the participant has been in t...,['Both males and females 0 YEARS - 150 YEARS'],None,None

In [18]:
df_expanded.to_csv('DEMO_codebook.csv', sep=',', encoding='utf-8')

In [19]:
dictionary_mapping = codebook_select_col[['Variable_Name']]

In [20]:
dictionary_mapping = dictionary_mapping.drop_duplicates(subset='Variable_Name', keep='first')

In [21]:
dictionary_mapping['Attribute'] = None
dictionary_mapping['attributeOf'] = None
dictionary_mapping['Unit'] = None
dictionary_mapping['Time'] = None
dictionary_mapping['Entity'] = None
dictionary_mapping['Role'] = None
dictionary_mapping['Relation'] = None
dictionary_mapping['inRelationTo'] = None
dictionary_mapping['wasDerivedFrom'] = None
dictionary_mapping['wasGeneratedBy'] = None

In [22]:
dictionary_mapping.reset_index(inplace=True, drop=True)

In [23]:
dictionary_mapping

,Variable_Name,Attribute,attributeOf,Unit,Time,Entity,Role,Relation,inRelationTo,wasDerivedFrom,wasGeneratedBy
0,SEQN,None,None,None,None,None,None,None,None,None,None
1,SDDSRVYR,None,None,None,None,None,None,None,None,None,None
2,RIDSTATR,None,None,None,None,None,None,None,None,None,None
3,RIDEXMON,None,None,None,None,None,None,None,None,None,None
4,RIAGENDR,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
174,DMDMARTZ,None,None,None,None,None,None,None,None,None,None
175,DMDYRUSZ,None,None,None,None,None,None,None,None,None,None
176,WTINTPRP,None,None,None,None,None,None,None,None,None,None
177,WTMECPRP,None,None,None,None,None,None,None,None,None,None
178,DMDYRUSR,None,None,None,None,None,None,None,None,None,None

In [24]:
dictionary_mapping.rename(columns={"Variable_Name": "Column"}, inplace=True)

In [25]:
dictionary_mapping.to_csv('DEMO_dictionary_mapping.csv', sep=',', encoding='utf-8')